---

- name: Create Nginx directory
  tags: 'Nginx'
  become: yes
  file:
    path: "{{ nginx_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
    state: directory


- name: Configure compose
  tags: 'Nginx'
  become: yes
  template:
    src: nginx-docker-compose.yaml.j2
    dest: "{{ nginx_dir }}/docker-compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Run docker compose
  tags: 'Nginx'
  become: yes
  docker_compose:
    project_src: "{{ nginx_dir }}"
    pull: yes
    state: present
    remove_orphans: yes
    recreate: always


