---
# Team 46
# Haoyue Xie 1003068 @Melbourne
# Jiayu Li 713551 @Melbourne
# Ruqi Li 1008342 @Melbourne
# Yi Zhang 1032768 @Melbourne
# Zimeng Jia 978322 @Hebei, China

- name: adding docker users (for use without sudo)
  user:
    name: "ubuntu"
    append: yes
    groups: docker
  become: true
  with_items: "['ubuntu']"

- name: Create CouchDb directory
  tags: 'couch_slave2'
  become: yes
  file:
    path: "couch_slave2"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
    state: directory

- name: Configure compose
  tags: 'couch_slave2'
  become: yes
  template:
    src: slave2-docker-compose.yaml.j2
    dest: "couch_slave2/docker-compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Create CouchDb directory
  tags: 'etc'
  become: yes
  file:
    path: "./couch_slave2/etc"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
    state: directory

- name: Run docker compose
  tags: 'couch_slave2'
  become: yes
  docker_compose:
    project_src: "couch_slave2"
    pull: yes
    state: present
    remove_orphans: yes
    recreate: always

- name: upload the subnode script
  become: yes
  copy:
    src: ./setupcouch.sh
    dest: /home/ubuntu/
    mode: 0777

- name: execute the subnode script
  become: yes
  shell: /home/ubuntu/setupcouch.sh




