---
- name: adding docker users (for use without sudo)
  user:
    name: "ubuntu"
    append: yes
    groups: docker
  become: true
  with_items: "['ubuntu']"

- name: Create CouchDb directory
  tags: 'couch_slave2'
  become: yes
  file:
    path: "couch_slave2"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
    state: directory

- name: Configure compose
  tags: 'couch_slave2'
  become: yes
  template:
    src: slave2-docker-compose.yaml.j2
    dest: "couch_slave2/docker-compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Run docker compose
  tags: 'couch_slave2'
  become: yes
  docker_compose:
    project_src: "couch_slave2"
    pull: yes
    state: present
    remove_orphans: yes
    recreate: always




