# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: Vol-1-75
    vol_size: 75
  - vol_name: Vol-2-75
    vol_size: 75
  - vol_name: Vol-3-75
    vol_size: 75
  - vol_name: Vol-4-25
    vol_size: 25


# Security group
security_groups:
  - name: s_ssh
    description: "Security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: s_http
    description: "Security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: instance1
    volumes: ['Vol-1-75']
  - name: instance2
    volumes: ['Vol-2-75']
  - name: instance3
    volumes: ['Vol-3-75']
  - name: instance4
    volumes: ['Vol-4-25']


instance_image: 45225edb-66d8-4fd0-bf41-132a31a18166
instance_key_name: winkey
instance_flavor: uom.mse.2c9g
