# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: demo-03-vol-1
    vol_size: 10
  - vol_name: demo-03-vol-2
    vol_size: 10

# Security group
security_groups:
  - name: demo_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: demo-03
    volumes: ['demo-03-vol-1', 'demo-03-vol-2']

instance_image: 45225edb-66d8-4fd0-bf41-132a31a18166
instance_key_name: testdemo
instance_flavor: uom.general.1c4g
