- hosts: all
  vars_files:
      - host_vars/docker.yaml
  gather_facts: true

  roles:
    - role: common
    - role: volumes
    - role: docker


- hosts: all

  tasks:
    - name: Install NPM and Nodejs
      become: yes
      apt:
        name: nodejs
        state: present

  tasks:
  - name: adding docker users (for use without sudo)
    user:
      name: "ubuntu"
      append: yes
      groups: docker
    become: true
    with_items: "['ubuntu']"

