- hosts: localhost
  vars_files:
    - host_vars/nectar.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance

- hosts: COMP90024
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/winkey.pem
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
    - name: Add proxy in /etc/environment
      become: yes
      blockinfile:
        path: /etc/environment
        block: |
          HTTP_PROXY=http://wwwproxy.unimelb.edu.au:8000/
          HTTPS_PROXY=http://wwwproxy.unimelb.edu.au:8000/
          http_proxy=http://wwwproxy.unimelb.edu.au:8000/
          https_proxy=http://wwwproxy.unimelb.edu.au:8000/
          no_proxy = “localhost,127.0.0.1,localaddress,127.16.0.0/12,melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au”


    - name: Reboot machine
      become: yes
      reboot:
        reboot_timeout: 3000

    - name: Install vim
      become: yes
      apt:
        name: ['vim']
        state: latest
        install_recommends: no
        update_cache: yes


    - name: update apt cache
      become: true
      apt:
        update_cache : yes
